# Site settings
title: idness
email: adam.silverman@hotmail.com
description: > # this means to ignore newlines until "baseurl:"
  The id of ness.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://idness.com" # the base hostname & protocol for your site
github_username:  abalone23
author:
  name: "Your Sidebar Name"

# Build settings
markdown: kramdown

theme: minima